# Cloud Run configuration for MedellínBot Webhook
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: medellinbot-webhook
  namespace: default
  annotations:
    run.googleapis.com/execution-environment: gen2
    run.googleapis.com/cpu-throttling: "false"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "100"
        run.googleapis.com/timeout-seconds: "30"
    spec:
      containerConcurrency: 80
      containers:
      - image: us-central1-docker.pkg.dev/PROJECT_ID/medellinbot/webhook:latest
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: "PROJECT_ID"
        - name: ENVIRONMENT
          value: "production"
        - name: ORCHESTRATOR_URL
          value: "https://medellinbot-orchestrator-PROJECT_ID.a.run.app"
        - name: REQUIRE_AUTH
          value: "true"
        - name: RATE_LIMIT_REQUESTS
          value: "1000"
        - name: RATE_LIMIT_WINDOW
          value: "3600"
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "2"
            memory: "512Mi"
          requests:
            cpu: "1"
            memory: "256Mi"
      serviceAccountName: medellinbot-service-account@PROJECT_ID.iam.gserviceaccount.com
  traffic:
  - percent: 100
    latestRevision: true